package com.lhcode.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallBenefit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.link_id
     *
     * @mbg.generated
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.customer_benefit
     *
     * @mbg.generated
     */
    private BigDecimal customerBenefit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.profit_percentage
     *
     * @mbg.generated
     */
    private Integer profitPercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.current_amount
     *
     * @mbg.generated
     */
    private Integer currentAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_benefit.recharge_money
     *
     * @mbg.generated
     */
    private Integer rechargeMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.id
     *
     * @return the value of litemall_benefit.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_benefit.id
     *
     * @param id the value for litemall_benefit.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.add_time
     *
     * @return the value of litemall_benefit.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.link_id
     *
     * @return the value of litemall_benefit.link_id
     *
     * @mbg.generated
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_benefit.link_id
     *
     * @param linkId the value for litemall_benefit.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.customer_id
     *
     * @return the value of litemall_benefit.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_benefit.customer_id
     *
     * @param customerId the value for litemall_benefit.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.customer_benefit
     *
     * @return the value of litemall_benefit.customer_benefit
     *
     * @mbg.generated
     */
    public BigDecimal getCustomerBenefit() {
        return customerBenefit;
    }

    public void setCustomerBenefit(BigDecimal customerBenefit) {
        this.customerBenefit = customerBenefit;
    }

    public Integer getProfitPercentage() {
        return profitPercentage;
    }

    public void setProfitPercentage(Integer profitPercentage) {
        this.profitPercentage = profitPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.current_amount
     *
     * @return the value of litemall_benefit.current_amount
     *
     * @mbg.generated
     */
    public Integer getCurrentAmount() {
        return currentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_benefit.current_amount
     *
     * @param currentAmount the value for litemall_benefit.current_amount
     *
     * @mbg.generated
     */
    public void setCurrentAmount(Integer currentAmount) {
        this.currentAmount = currentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_benefit.recharge_money
     *
     * @return the value of litemall_benefit.recharge_money
     *
     * @mbg.generated
     */
    public Integer getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_benefit.recharge_money
     *
     * @param rechargeMoney the value for litemall_benefit.recharge_money
     *
     * @mbg.generated
     */
    public void setRechargeMoney(Integer rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", linkId=").append(linkId);
        sb.append(", customerId=").append(customerId);
        sb.append(", customerBenefit=").append(customerBenefit);
        sb.append(", profitPercentage=").append(profitPercentage);
        sb.append(", currentAmount=").append(currentAmount);
        sb.append(", rechargeMoney=").append(rechargeMoney);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallBenefit other = (LitemallBenefit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getLinkId() == null ? other.getLinkId() == null : this.getLinkId().equals(other.getLinkId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getCustomerBenefit() == null ? other.getCustomerBenefit() == null : this.getCustomerBenefit().equals(other.getCustomerBenefit()))
            && (this.getProfitPercentage() == null ? other.getProfitPercentage() == null : this.getProfitPercentage().equals(other.getProfitPercentage()))
            && (this.getCurrentAmount() == null ? other.getCurrentAmount() == null : this.getCurrentAmount().equals(other.getCurrentAmount()))
            && (this.getRechargeMoney() == null ? other.getRechargeMoney() == null : this.getRechargeMoney().equals(other.getRechargeMoney()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getLinkId() == null) ? 0 : getLinkId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getCustomerBenefit() == null) ? 0 : getCustomerBenefit().hashCode());
        result = prime * result + ((getProfitPercentage() == null) ? 0 : getProfitPercentage().hashCode());
        result = prime * result + ((getCurrentAmount() == null) ? 0 : getCurrentAmount().hashCode());
        result = prime * result + ((getRechargeMoney() == null) ? 0 : getRechargeMoney().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        addTime("add_time", "addTime", "BIGINT", false),
        updateTime("update_time", "updateTime", "BIGINT", false),
        linkId("link_id", "linkId", "INTEGER", false),
        customerId("customer_id", "customerId", "INTEGER", false),
        customerBenefit("customer_benefit", "customerBenefit", "INTEGER", false),
        profitPercentage("profit_percentage", "profitPercentage", "DECIMAL", false),
        currentAmount("current_amount", "currentAmount", "INTEGER", false),
        rechargeMoney("recharge_money", "rechargeMoney", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_benefit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}