package com.lhcode.litemall.db.dao;

import com.lhcode.litemall.db.domain.LitemallBenefit;
import com.lhcode.litemall.db.domain.LitemallBenefitExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface LitemallBenefitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    long countByExample(LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int insert(LitemallBenefit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int insertSelective(LitemallBenefit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBenefit selectOneByExample(LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBenefit selectOneByExampleSelective(@Param("example") LitemallBenefitExample example, @Param("selective") LitemallBenefit.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallBenefit> selectByExampleSelective(@Param("example") LitemallBenefitExample example, @Param("selective") LitemallBenefit.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    List<LitemallBenefit> selectByExample(LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBenefit selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallBenefit.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    LitemallBenefit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallBenefit record, @Param("example") LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallBenefit record, @Param("example") LitemallBenefitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallBenefit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_benefit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallBenefit record);
}