package com.lhcode.litemall.db.dao;

import com.lhcode.litemall.db.domain.LitemallSpreadOrder;
import com.lhcode.litemall.db.domain.LitemallSpreadOrderExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface LitemallSpreadOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int insert(LitemallSpreadOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSpreadOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadOrder selectOneByExample(LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadOrder selectOneByExampleSelective(@Param("example") LitemallSpreadOrderExample example, @Param("selective") LitemallSpreadOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallSpreadOrder> selectByExampleSelective(@Param("example") LitemallSpreadOrderExample example, @Param("selective") LitemallSpreadOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    List<LitemallSpreadOrder> selectByExample(LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSpreadOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    LitemallSpreadOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSpreadOrder record, @Param("example") LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSpreadOrder record, @Param("example") LitemallSpreadOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSpreadOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spread_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSpreadOrder record);

    BigDecimal userBenfit(Map map);

}