package com.lhcode.litemall.db.dao;

import com.lhcode.litemall.db.domain.LitemallViplevel;
import com.lhcode.litemall.db.domain.LitemallViplevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallViplevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    long countByExample(LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int insert(LitemallViplevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int insertSelective(LitemallViplevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallViplevel selectOneByExample(LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallViplevel selectOneByExampleSelective(@Param("example") LitemallViplevelExample example, @Param("selective") LitemallViplevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallViplevel> selectByExampleSelective(@Param("example") LitemallViplevelExample example, @Param("selective") LitemallViplevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    List<LitemallViplevel> selectByExample(LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallViplevel selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallViplevel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    LitemallViplevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallViplevel record, @Param("example") LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallViplevel record, @Param("example") LitemallViplevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallViplevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_viplevel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallViplevel record);


    /**
     * 查询会员数量
     * @return
     */
    int selectCount();
}