package com.lhcode.litemall.db.dao;

import com.lhcode.litemall.db.domain.LitemallSpreadclass;
import com.lhcode.litemall.db.domain.LitemallSpreadclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallSpreadclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    long countByExample(LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int insert(LitemallSpreadclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSpreadclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadclass selectOneByExample(LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadclass selectOneByExampleSelective(@Param("example") LitemallSpreadclassExample example, @Param("selective") LitemallSpreadclass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallSpreadclass> selectByExampleSelective(@Param("example") LitemallSpreadclassExample example, @Param("selective") LitemallSpreadclass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    List<LitemallSpreadclass> selectByExample(LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSpreadclass selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSpreadclass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    LitemallSpreadclass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSpreadclass record, @Param("example") LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSpreadclass record, @Param("example") LitemallSpreadclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSpreadclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_spreadclass
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSpreadclass record);
}