package com.lhcode.litemall.db.dao;

import com.lhcode.litemall.db.domain.LitemallAccountWithdraw;
import com.lhcode.litemall.db.domain.LitemallAccountWithdrawExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface LitemallAccountWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    long countByExample(LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int insert(LitemallAccountWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAccountWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAccountWithdraw selectOneByExample(LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAccountWithdraw selectOneByExampleSelective(@Param("example") LitemallAccountWithdrawExample example, @Param("selective") LitemallAccountWithdraw.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallAccountWithdraw> selectByExampleSelective(@Param("example") LitemallAccountWithdrawExample example, @Param("selective") LitemallAccountWithdraw.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    List<LitemallAccountWithdraw> selectByExample(LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAccountWithdraw selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAccountWithdraw.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    LitemallAccountWithdraw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAccountWithdraw record, @Param("example") LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAccountWithdraw record, @Param("example") LitemallAccountWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAccountWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAccountWithdraw record);

    BigDecimal selectSumMoney(Map map);

}